### PR TITLE
Added the basics of the gh action

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by navendu-pottekkat** [comment]
@sayantan1413 Is this still a WIP?

Could you share what else is needed here? Let's try to fix this today. I will jump in on this.

**Comment by sayantan1413** [comment]
Hey @navendu-pottekkat till now the functionality supports deploying patterns using a URL. I am working next on deploying pattern through a pattern file.

**Comment by navendu-pottekkat** [comment]
@sayantan1413 Let's merge this then and you can add this functionality in a separate PR.

**Comment by sayantan1413** [comment]
Yup @navendu-pottekkat I can do that. And yes I guess we can merge this PR and test it out.

**Review by navendu-pottekkat — APPROVED** [review]

**Pull request merged**
